# Generated by Django 5.2.9 on 2026-08-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pblsh', 'Published'), ('drft', 'Draft')], max_length=10),
        ),
    ]
