"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import dj_database_url
import os
from pathlib import Path

from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

# بارگذاری متغیرهای محیطی از فایل .env
# Load environment variables from the .env file
load_dotenv(BASE_DIR / ".env")


SECRET_KEY = os.environ.get("SECRET_KEY")

if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is required.")

DEBUG = os.environ.get("DEBUG", "False").lower() == "true"


# ALLOWED_HOSTS = ['*']

ALLOWED_HOSTS = [
host.strip()
for host in os.environ.get(
"ALLOWED_HOSTS",
"127.0.0.1,localhost",
).split(",")
if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
origin.strip()
for origin in os.environ.get(
"CSRF_TRUSTED_ORIGINS",
"",
).split(",")
if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'blog',
    'accounts',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        #  علاوه بر تمپلیتهای موجود در اپ های دیگر بیا و تمپلیت قرار بده برای پروژه ی اصلی (blog_website)
        'DIRS': [str(BASE_DIR.joinpath('templates'))],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# import os
# import dj_database_url
# فرض می‌کنیم BASE_DIR و DEBUG قبلاً در بالای تنظیمات تعریف شده‌اند:
# BASE_DIR = Path(__file__).resolve().parent.parent
# DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

DATABASE_URL = os.environ.get("DATABASE_URL")

# 🚨 یک لایه امنیتی مهندسی‌شده برای جلوگیری از خطای خاموش در سرور واقعی:
if not DEBUG and not DATABASE_URL:
    raise RuntimeError(
        "❌ خطا: متغیر DATABASE_URL در محیط Production تعریف نشده است!"
    )

# تنظیم نهایی و پایدار دیتابیس 🚀
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
        ssl_require=not DEBUG,
    )
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
"default": {
"BACKEND": "django.core.files.storage.FileSystemStorage",
},
"staticfiles": {
"BACKEND": (
"whitenoise.storage.CompressedManifestStaticFilesStorage"
),
},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LOGIN_REDIRECT_URL = "blog:posts_list"

if not DEBUG:
    # اعلام HTTPS اصلی به Django وقتی پشت Proxy مثل Render هستیم
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # ارسال کوکی‌ها فقط روی HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # اجبار تمام درخواست‌ها به HTTPS
    SECURE_SSL_REDIRECT = True

    # HSTS: اجبار مرورگر به استفاده از HTTPS برای یک سال
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True




